# Generated by Django 5.0.3 on 2024-06-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('dist', models.CharField(max_length=200)),
                ('imgs', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
