# Generated by Django 5.0.3 on 2024-06-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rentar_delete_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentar',
            name='adress',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentar',
            name='imgs',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
