# Generated by Django 5.0.3 on 2024-06-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_imgs_rentar_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_team',
            name='Name',
            field=models.CharField(max_length=255),
        ),
    ]
